// Generated by CoffeeScript 1.8.0
(function() {
  module.exports = {
    name: "Where are you?",
    listen: function(message, room, logger) {
      var body;
      body = message.body;
      if (/pat/i.test(body) && /where are you\?/i.test(body)) {
        return room.speak("I am in " + (process.cwd()), logger);
      }
    }
  };

}).call(this);
